### ISSUE TITLE
Missing Parentheses

### ISSUE THREAD

**Issue by oghenejivwe** [shivsahni/NSBrute#8]
File "NSBrute.py", line 33
    print bcolors.INFO+text+bcolors.ENDC+"\n"
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(bcolors.INFO+text+bcolors.ENDC+"\n")?

Also when i try installing requirement I get this error:
ERROR: Could not find a version that satisfies the requirement traceback (from -r requirements.txt (line 2)) (from versions: none)
ERROR: No matching distribution found for traceback (from -r requirements.txt (line 2))

**Comment by shivsahni** [comment]
Hey @oghenejivwe,

It works fine in my case. Tested it on multiple platforms. Can you check if you are using the suggested version of Python and required dependencies?
Closing this issue as of now, if the issue persists please feel free to re-open it.
